### ISSUE TITLE
How to overwrite kubeadm_config_patches default interfaces using this kind provider ?

### ISSUE THREAD

**Issue by maabik** [kyma-incubator/terraform-provider-kind#38] opened 2021-01-01 21:57 UTC
@jwillebrands @unicell  @pst @valentinvieriu @tehcyx 

In fact I want to translate this type of yaml code

  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "my-label2=true"

using this kind provider. In kind/schema_kind_config.go file, we have in func kindConfigNodeFields() map[string]*schema.Schema this
part of code:

		"kubeadm_config_patches": {
			Type:     schema.TypeList,
			Optional: true,
			Elem:     &schema.Schema{Type: schema.TypeString},
		},
How to be done for writing the corresponding kubeadmConfigPatches yaml code with  kyma-incubator/terraform-provider-kind.
Could you give me an example to use that please !

**Comment by tehcyx** [comment] 2021-01-02 23:39
Hi @maabik, as you asked the same question in your other [issue](https://github.com/kyma-incubator/terraform-provider-kind/issues/36), the way to do this is using the heredoc notation:
```hcl
resource "kind_cluster" "test" {
  name = "test"
  wait_for_ready = true
  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
        role = "control-plane"
        kubeadm_config_patches = [
        <<-INTF
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "ingress-ready=true"
        INTF
        ]
    }
  }
}
```
make sure that the indentation is correct or this won't work.

As a duplicate of your initial issue, I will close this as it is answered now in both issues.

**Closed as completed by tehcyx** 2021-01-02 23:39 UTC
